### ISSUE TITLE
[Meta] Move off of Jellyfin

### ISSUE THREAD

**Issue by jaredallard** [tritonmedia/triton#5]
Due to Jellyfin declining support for S3 media files, I think it's time that we move away from Jellyfin. It's not scaleable and is very heavy compared to what we need (no transcoding needed, thin user permissions).

In line with this, we have a few items to get off of Jellyfin.

* [x] Create an identifier service to identify media and grab metadata (#6)
* [ ] Create a web ui (player) to play media (#7)
* [ ] [non-mvp] Android App w/ Web UI
